### PR TITLE
Skip anchor links in the current doc

### PR DESCRIPTION
**Pull request by surkova**
Internal anchor links should be skipped

### CODE REVIEW

**Comment by Undeterminant** [comment]
Thank you so much for the changes! I also appreciate the conversion of tabs to spaces— I made this was a while ago before I started using PEP8 for everything. I'll go through the remainder of the lints to make sure that everything is good, then do a version bump.

**Comment by surkova** [comment]
@Undeterminant thank you for updating the project! One more request: [the binary that you published](https://pypi.python.org/pypi/markdown-newtab/0.2.0) doesn't get caught by `pip` when I try the simplest `pip install markdown-newtab`, even though my ubuntu is x86_64. Maybe renaming would help?

**Comment by surkova** [comment]
I figured that you've upgraded your build to python 3.5 and I'm using 2.7, so pip is basically ignoring your package when I try to upgrade my version:
```
Analyzing links from page https://pypi.python.org/simple/markdown-newtab/
    Found link https://pypi.python.org/packages/any/m/markdown-newtab/markdown-newtab-0.2.0.linux-x86_64.tar.gz#md5=6da305c79d46d846a4e1ebafe7b12a1d (from https://pypi.python.org/simple/markdown-newtab/), version: 0.2.0.linux-x86_64
    Found link https://pypi.python.org/packages/source/m/markdown-newtab/markdown-newtab-0.1.0.tar.gz#md5=db220ff9dc8073b7f49845c1b94f93f8 (from https://pypi.python.org/simple/markdown-newtab/), version: 0.1.0
  "GET /packages/source/m/markdown-newtab/markdown-newtab-0.1.0.tar.gz HTTP/1.1" 200 3735
  Downloading markdown-newtab-0.1.0.tar.gz
```

**Comment by Undeterminant** [comment]
Huh, you're right. I accidentally did a bdist upload instead of an sdist upload. Fixed.

**Comment by surkova** [comment]
Thank you!

**Pull request merged**
